### ISSUE TITLE
More informations

### ISSUE THREAD

**Issue by Banou26** [eai04191/parcel-wtf#1]
I have my idea about what's the problem you're referring to by sending the logs but i'm not sure so i'll ask anyways.

There's 700ms for 3 files but the actual parcel run stops around 1.2s afterwards.
Is that the thing you're referring to ?

I think it may be related to Parcel's cache.

Also, if you're interested in using 'unstable'(its pretty stable tho) versions, there's the v2 of Parcel which is available on `parcel@next`, e.g `yarn add parcel@next -D`

**Comment by eai04191** [comment]
This repository is published as sample code of question site. Thanks for the help anyway.

Original Question: https://teratail.com/questions/241239

The question is in Japanese, but the point is that webmanifest is not created in `dtst/`

Also, I was using `parcel@next` until just yesterday, but I stopped using it because I could not build it ...

**Comment by Banou26** [comment]
There seem to be quite a bit of issues already opened on Parcel regarding web manifests so they already know about it.

This is perfect since i'm learning japanese right now, it'll be a little exercise :)

Alrighty then 👍 
Have a great day
